name: yeast
root: datasets/Yeast
level: level1
type: semisupervise
re_generate: False

hidden_dim: 512
embedding_dim: 128
dropout_rate: 0.1
learning_rate: 0.01
num_epoch: 1200
patience: 35

alpha: 0.2
num_heads: 8