name: yeast
root: datasets/Yeast
level: level1
re_generate: False
is_supervise: False

hidden_dim: 512
embedding_dim: 32
dropout_rate: 0.1
learning_rate: 0.005
num_epoch: 1200
patience: 35

alpha: 0.2
num_heads: 8